version: 0.22.{build}

pull_requests:
  do_not_increment_build_number: true

configuration: Release

shallow_clone: true

image: Visual Studio 2017

init:
- ps: >
    if($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_TAG_NAME.StartsWith("v") -eq $true) {

      Set-AppVeyorBuildVariable -Name APPVEYOR_BUILD_VERSION -Value $env:APPVEYOR_REPO_TAG_NAME.Substring(1)

    }
  

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  GOOGLE_API_KEY:
    secure: pnYRPfFKB+uub3hlM9mX2q3CzVKsqCg/EM/lFZ2DN6yePU4wBbhr0PhBf3dDVgU4

before_build:
  - msbuild src\GoogleMapsForNET.sln /t:restore

build_script:
- cmd: msbuild src\GoogleMapsForNET.sln /t:build /p:Configuration=Release /verbosity:minimal

after_build:
- cmd: nuget pack gmaps-api-net.nuspec -version %APPVEYOR_BUILD_VERSION%

test_script:
- ps: >-
    
    $DLL_LOCATION=".\src\Google.Maps.Test\bin\Release\net461\Google.Maps.Test.dll"
    
    nunit3-console $DLL_LOCATION --labels=All --where:"cat!=ValueTesting" "--result=testresults.xml;format=AppVeyor"

    if($? -eq $true) {

      nunit3-console $DLL_LOCATION --labels=All --where:"cat!=ValueTesting" "--result=testresults2.xml;format=AppVeyor"

    }

artifacts:
- path: '*.nupkg'
  name: NuGetPackage

deploy:
- provider: NuGet
  api_key:
    secure: 2SwDMmXZZtgoLWsldKZ8GCu9rZXpO5quTYtSNJQSeeiqDjnmo0OfutNVcH3jsfpj
  artifact: NugetPackage
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: bupArXj8lz6RLLO8GPwyRnbGwcmyjg4MvmlBsYD8x+euC9YS5G5y9jaSPCpS7tsX
  artifact: NugetPackage
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Email
  to:
  - ericnewton76@gmail.com
  subject: Gmaps-api-net build completed.
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

# Temporary workaround for AppVeyor -> NuGet connectivity issues
hosts:
  api.nuget.org: 93.184.221.200